apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: axion-backend-cert
  namespace: axion
spec:
  secretName: axion-backend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.axion.krishlabs.tech
  dnsNames:
  - api.axion.krishlabs.tech
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: axion-ws-relayer-cert
  namespace: axion
spec:
  secretName: axion-ws-relayer-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wss.axion.krishlabs.tech
  dnsNames:
  - wss.axion.krishlabs.tech
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: axion-depin-ws-relayer-cert
  namespace: axion
spec:
  secretName: axion-depin-ws-relayer-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wss.depin.axion.krishlabs.tech
  dnsNames:
  - wss.depin.axion.krishlabs.tech
