apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: decloud-backend-cert
  namespace: decloud
spec:
  secretName: decloud-backend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.decloud.krishlabs.tech
  dnsNames:
  - api.decloud.krishlabs.tech
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: decloud-ws-relayer-cert
  namespace: decloud
spec:
  secretName: decloud-ws-relayer-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wss.decloud.krishlabs.tech
  dnsNames:
  - wss.decloud.krishlabs.tech
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: decloud-depin-ws-relayer-cert
  namespace: decloud
spec:
  secretName: decloud-depin-ws-relayer-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wss.depin.decloud.krishlabs.tech
  dnsNames:
  - wss.depin.decloud.krishlabs.tech
